### ISSUE TITLE
How to kick off the query

### ISSUE THREAD

**Issue by cburns352** [wimpyprogrammer/conditional-expression-parser#1]
It took me a minute to figure out how to run the query.  First I was trying to click [enter] and things like that.  Giving up in frustration I clicked away from the textbox and then it went.  Maybe add a fake button to make it more obvious?

**Comment by wimpyprogrammer** [comment]
Good point; the click-away method is something I used in development and got used to, but it's certainly confusing.  I just released 1.1.0 (884a6b362fa063cd473c30e5168277ffd4fcf936) which adds an explicit submit button to make the UI more obvious.
