### ISSUE TITLE
Final column to calculate the result for me?

### ISSUE THREAD

**Issue by cburns352** [wimpyprogrammer/conditional-expression-parser#2]
I don't remember a lot about truth tables so maybe I'm suggesting something that doesn't make sense, but it seems like a neat addition would be to add a column to the right to show me the result of each row.

**Comment by wimpyprogrammer** [comment]
Compared to the truth tables in [the Wikipedia article](http://en.wikipedia.org/wiki/Truth_table) I can see what you mean.  Each column displays either a condition or the result of an operation.  My tables are quite different so I probably need to drop the "truth table" label to avoid confusion.

But to be clear, if I did add a new column showing the result then every row would display TRUE.  When I (erroneously) refer to a truth table, what I'm trying to say is, "here are all of the combinations for which this expression would evaluate to true."
